# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Coagulation With Hemophiliacs 
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
    <div align="center">
    <p>
    <h1> Who Are We</h1> 
    We are a Online social networking support community for everyone affected by a bleeding disorder a community of    members,           supporters and healthcare professionals.
    </p>
    </div>
    
    <div align="center">
    <p>
    <h1> What We Do</h1> 
    We help people with bleeding disorders to lead fulfilling lives, make informed choices and to support and inspire     others.
    </p>
    </div>
    
    <div align="center">
    <p>
    <h1> What Is Our Goal</h1> 
    To set up an online registry for hemophilia patients, reach out every member via whatsapp and establish online community of Coagulation between Hemophilics to support each other for their wellbeing.
    </p>
    </div>
   
  header_text_feature_image:
  footer_text: >
   Built by <a>Anil Phani</a> And <a>Sunil Phani</a> <a>News</a>
  # Icons
  rss: false
  email_address: k.anilphani@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: #"rohanchandra/type-theme"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "@sunilphani"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-89125404-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
gems:
  - jekyll-feed
